using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Content.Client.GameTicking.Managers;

namespace Content.Client.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class ShiftSettingsWindow : DefaultWindow
{
    [Dependency] private IClientConsoleHost _console = default!;
    [Dependency] private IGameTiming _gameTiming = default!;
    [Dependency] private IEntitySystemManager _entitySystem = default!;

    private readonly ClientGameTicker _gameTicker;
    private readonly ButtonGroup _timeModeButtonGroup = new();

    public ShiftSettingsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();

        // Set up the button group for radio button behavior
        HoursFromNowCheckbox.Group = _timeModeButtonGroup;
        HoursFromRoundStartCheckbox.Group = _timeModeButtonGroup;

        SetShiftEndTimeButton.OnPressed += OnSetShiftEndTime;
        ClearShiftEndTimeButton.OnPressed += OnClearShiftEndTime;
        ShiftEndAutoCallCheckbox.OnToggled += OnAutoCallToggled;

        // Initialize the checkbox to checked by default (server default is true)
        // Note: This window doesn't sync with server state changes made by other admins or other means.
        // The checkbox reflects the default state and updates when toggled in this window.
        ShiftEndAutoCallCheckbox.Pressed = true;
        UpdateAutoCallStatus(true);
    }

    private void OnSetShiftEndTime(Button.ButtonEventArgs args)
    {
        if (string.IsNullOrWhiteSpace(ShiftEndTimeInput.Text))
            return;

        if (double.TryParse(ShiftEndTimeInput.Text, out var hours))
        {
            // Determine which mode is selected
            var fromNow = HoursFromNowCheckbox.Pressed;
            var mode = fromNow ? "now" : "roundstart";

            _console.ExecuteCommand($"setshiftendtime {hours} {mode}");
            ShiftEndTimeInput.Text = string.Empty;
            UpdateCurrentShiftEndLabel(hours, fromNow);
        }
    }

    private void OnClearShiftEndTime(Button.ButtonEventArgs args)
    {
        _console.ExecuteCommand("setshiftendtime 0");
        ShiftEndTimeInput.Text = string.Empty;
        CurrentShiftEndLabel.Text = Loc.GetString("administration-shift-settings-no-shift-end");
    }

    private void OnAutoCallToggled(BaseButton.ButtonToggledEventArgs args)
    {
        _console.ExecuteCommand($"setshiftendshuttle {args.Pressed.ToString().ToLower()}");
        UpdateAutoCallStatus(args.Pressed);
    }

    private void UpdateAutoCallStatus(bool enabled)
    {
        ShiftEndAutoCallStatus.Text = enabled
            ? Loc.GetString("administration-shift-settings-auto-call-enabled")
            : Loc.GetString("administration-shift-settings-auto-call-disabled");
    }

    private void UpdateCurrentShiftEndLabel(double hours, bool fromNow)
    {
        TimeSpan endTime;
        if (fromNow)
        {
            endTime = _gameTiming.RealTime + TimeSpan.FromHours(hours);
        }
        else
        {
            // Calculate from round start
            var roundStartRealTime = _gameTiming.RealTime - (_gameTiming.CurTime - _gameTicker.RoundStartTimeSpan);
            endTime = roundStartRealTime + TimeSpan.FromHours(hours);
        }

        CurrentShiftEndLabel.Text = Loc.GetString("administration-shift-settings-shift-end-set",
            ("time", endTime.ToString(@"d\:hh\:mm\:ss")));
    }
}
