using System.Linq;
using Content.Client.Resources;
using Content.Client.Viewport;
using Content.Shared.DeviceNetwork;
using Content.Shared.SurveillanceCamera;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics;
using Robust.Shared.Prototypes;

namespace Content.Client.SurveillanceCamera.UI;

[GenerateTypedNameReferences]
public sealed partial class SurveillanceCameraMonitorWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IResourceCache _resourceCache = default!;

    public event Action<string>? CameraSelected;
    public event Action<string>? SubnetOpened;
    public event Action? CameraRefresh;
    public event Action? SubnetRefresh;
    public event Action? CameraSwitchTimer;
    public event Action? CameraDisconnect;

    private string _currentAddress = string.Empty;
    private bool _isSwitching;
    private readonly FixedEye _defaultEye = new();
    // _CS Start: Cache camera/subnet data to avoid rebuilding UI lists when state is unchanged.
    private readonly Dictionary<string, string> _cameraCache = new();
    private readonly Dictionary<string, int> _subnetMap = new();
    private readonly HashSet<string> _subnetCache = new();
    // _CS End: Cache camera/subnet data to avoid rebuilding UI lists when state is unchanged.

    private string? SelectedSubnet
    {
        get
        {
            if (SubnetSelector.ItemCount == 0
                || SubnetSelector.SelectedMetadata == null)
            {
                return null;
            }

            return (string) SubnetSelector.SelectedMetadata;
        }
    }

    public SurveillanceCameraMonitorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // This could be done better. I don't want to deal with stylesheets at the moment.
        var texture = _resourceCache.GetTexture("/Textures/Interface/Nano/square_black.png");
        var shader = _prototypeManager.Index<ShaderPrototype>("CameraStatic").Instance().Duplicate();

        // _CS Start: Lower viewport cost for surveillance feeds by reducing size and render rate.
        // CCTV feeds do not need full-resolution world rendering; keep this smaller to
        // reduce per-frame viewport/light target memory pressure when watching broadcasts.
        CameraView.ViewportSize = new Vector2i(320, 320);
        CameraView.FixedRenderScale = 1;
        CameraView.StretchMode = ScalingViewportStretchMode.Nearest;
        CameraView.MaxRenderRate = 20f;
        // _CS End: Lower viewport cost for surveillance feeds by reducing size and render rate.
        CameraView.Eye = _defaultEye; // sure
        CameraViewBackground.Stretch = TextureRect.StretchMode.Scale;
        CameraViewBackground.Texture = texture;
        CameraViewBackground.ShaderOverride = shader;

        SubnetList.OnItemSelected += OnSubnetListSelect;

        SubnetSelector.OnItemSelected += args =>
        {
            // piss
            SubnetOpened!((string) args.Button.GetItemMetadata(args.Id)!);
        };
        SubnetRefreshButton.OnPressed += _ => SubnetRefresh!();
        CameraRefreshButton.OnPressed += _ => CameraRefresh!();
        CameraDisconnectButton.OnPressed += _ => CameraDisconnect!();
    }


    // The UI class should get the eye from the entity, and then
    // pass it here so that the UI can change its view.
    public void UpdateState(IEye? eye, HashSet<string> subnets, string activeAddress, string activeSubnet, Dictionary<string, string> cameras)
    {
        _currentAddress = activeAddress;
        SetCameraView(eye);

        if (subnets.Count == 0)
        {
            // _CS Start: Keep subnet selector stable in empty-state and skip unnecessary rebuild work.
            UpdateSubnetSelectorEmpty();
            PopulateCameraList(cameras);
            // _CS End: Keep subnet selector stable in empty-state and skip unnecessary rebuild work.
            return;
        }

        // _CS Start: Rebuild subnet selector only when the set actually changes.
        UpdateSubnetSelector(subnets);
        // _CS End: Rebuild subnet selector only when the set actually changes.

        // That way, we have *a* subnet selected if this is ever opened.
        if (string.IsNullOrEmpty(activeSubnet))
        {
            SubnetOpened!(subnets.First());
            return;
        }

        if (_subnetMap.TryGetValue(activeSubnet, out var subnetId))
        {
            if (SubnetSelector.SelectedId != subnetId)
            {
                SubnetSelector.Select(subnetId);
            }
        }

        PopulateCameraList(cameras);
    }

    private void PopulateCameraList(Dictionary<string, string> cameras)
    {
        // _CS Start: Short-circuit camera list updates when nothing changed.
        if (DictionariesEqual(_cameraCache, cameras))
        {
            return;
        }

        _cameraCache.Clear();
        foreach (var (address, name) in cameras)
        {
            _cameraCache[address] = name;
        }
        // _CS End: Short-circuit camera list updates when nothing changed.

        var entries = cameras.Select(i => new ItemList.Item(SubnetList) {
            Text = $"{i.Value}: {i.Key}",
            Metadata = i.Key
        }).ToList();
        entries.Sort((a, b) => string.Compare(a.Text, b.Text, StringComparison.Ordinal));
        SubnetList.SetItems(entries, (a,b) => string.Compare(a.Text, b.Text));
    }

    private void SetCameraView(IEye? eye)
    {
        var eyeChanged = eye != CameraView.Eye || CameraView.Eye == null;
        CameraView.Eye = eye ?? _defaultEye;
        CameraView.Visible = !eyeChanged && !_isSwitching;
        CameraDisconnectButton.Disabled = eye == null;

        if (eye != null)
        {
            if (!eyeChanged)
            {
                return;
            }

            _isSwitching = true;
            CameraViewBackground.Visible = true;
            CameraStatus.Text = Loc.GetString("surveillance-camera-monitor-ui-status",
                ("status", Loc.GetString("surveillance-camera-monitor-ui-status-connecting")),
                ("address", _currentAddress));
            CameraSwitchTimer!();
        }
        else
        {
            CameraViewBackground.Visible = true;
            CameraStatus.Text = Loc.GetString("surveillance-camera-monitor-ui-status-disconnected");
        }
    }

    public void OnSwitchTimerComplete()
    {
        _isSwitching = false;
        CameraView.Visible = CameraView.Eye != _defaultEye;
        CameraViewBackground.Visible = CameraView.Eye == _defaultEye;
        CameraStatus.Text = Loc.GetString("surveillance-camera-monitor-ui-status",
                            ("status", Loc.GetString("surveillance-camera-monitor-ui-status-connected")),
                            ("address", _currentAddress));
    }

    private int AddSubnet(string subnet)
    {
        var name = subnet;
        if (_prototypeManager.TryIndex<DeviceFrequencyPrototype>(subnet, out var frequency))
        {
            name = Loc.GetString(frequency.Name ?? subnet);
        }

        SubnetSelector.AddItem(name);
        SubnetSelector.SetItemMetadata(SubnetSelector.ItemCount - 1, subnet);

        return SubnetSelector.ItemCount - 1;
    }

    private void OnSubnetListSelect(ItemList.ItemListSelectedEventArgs args)
    {
        CameraSelected!((string) SubnetList[args.ItemIndex].Metadata!);
    }

    // _CS Start: Consolidate subnet selector diffing helpers to avoid redundant UI churn.
    private void UpdateSubnetSelector(HashSet<string> subnets)
    {
        if (!_subnetCache.SetEquals(subnets) || SubnetSelector.Disabled)
        {
            _subnetCache.Clear();
            _subnetCache.UnionWith(subnets);

            SubnetSelector.Clear();
            _subnetMap.Clear();
            SubnetSelector.Disabled = false;

            foreach (var subnet in subnets)
            {
                var id = AddSubnet(subnet);
                _subnetMap.Add(subnet, id);
            }
        }
    }

    private void UpdateSubnetSelectorEmpty()
    {
        _subnetCache.Clear();
        _subnetMap.Clear();

        if (SubnetSelector.Disabled && SubnetSelector.ItemCount == 1)
        {
            return;
        }

        SubnetSelector.Clear();
        SubnetSelector.AddItem(Loc.GetString("surveillance-camera-monitor-ui-no-subnets"));
        SubnetSelector.Disabled = true;
    }

    private static bool DictionariesEqual(Dictionary<string, string> left, Dictionary<string, string> right)
    {
        if (left.Count != right.Count)
        {
            return false;
        }

        foreach (var (key, value) in right)
        {
            if (!left.TryGetValue(key, out var leftValue) || leftValue != value)
            {
                return false;
            }
        }

        return true;
    }
    // _CS End: Consolidate subnet selector diffing helpers to avoid redundant UI churn.
}
