[game]
hostname = "[EN][MRP][18+] Kritters Refuge"
desc = "(18+, WHITELIST ONLY.) Welcome to Kritters Refuge, set in the Coyote system! We're a fork of Frontier focused on (Erotic) Roleplay, both serious and silly. With features like the Roleplay Incentive system, you can easily find yourself immersed in a dangerous frontier of possibility (and profit). So, come on down, we have a shuttle just waiting for you!"

[infolinks]
discord    = "https://discord.gg/rnxJk2Rf3m"
github     = "https://github.com/Dizztrikt/Kritters-Refuge"
website    = ""
wiki       = ""
patreon    = ""
bug_report = ""
appeal     = ""

[hub]
tags = "18+,lang:en-US,region:am_n_e,rp:med,no_tag_infer"
