using Content.Shared.Atmos;
using Content.Shared.Atmos.Monitor.Components;
using Content.Shared.Atmos.Piping.Unary.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Atmos.Monitor.UI.Widgets;

[GenerateTypedNameReferences]
public sealed partial class ScrubberControl : BoxContainer
{
    private GasVentScrubberData _data;
    private string _address;

    public event Action<string, IAtmosDeviceData>? ScrubberDataChanged;
	public event Action<IAtmosDeviceData>? ScrubberDataCopied;

    private CheckBox _enabled => CEnableDevice;
    private CollapsibleHeading _addressLabel => CAddress;
    private OptionButton _pumpDirection => CPumpDirection;
    private FloatSpinBox _volumeRate => CVolumeRate;
    private CheckBox _wideNet => CWideNet;
    private Button _copySettings => CCopySettings;

    private GridContainer _gases => CGasContainer;
    private Dictionary<Gas, Button> _gasControls = new();
    private Dictionary<Gas, FloatSpinBox> _gasLimitControls = new();

    public ScrubberControl(GasVentScrubberData data, string address)
    {
        RobustXamlLoader.Load(this);

        Name = address;

        _data = data;
        _address = address;

        _addressLabel.Title = Loc.GetString("air-alarm-ui-atmos-net-device-label", ("address", $"{address}"));

        _enabled.Pressed = data.Enabled;
        _enabled.OnToggled += _ =>
        {
            _data.Enabled = _enabled.Pressed;
            ScrubberDataChanged?.Invoke(_address, _data);
        };

        _wideNet.Pressed = data.WideNet;
        _wideNet.OnToggled += _ =>
        {
            _data.WideNet = _wideNet.Pressed;
            ScrubberDataChanged?.Invoke(_address, _data);
        };

        _volumeRate.Value = _data.VolumeRate;
        _volumeRate.OnValueChanged += _ =>
        {
            _data.VolumeRate = _volumeRate.Value;
            ScrubberDataChanged?.Invoke(_address, _data);
        };
        _volumeRate.IsValid += value => value >= 0;

        foreach (var value in Enum.GetValues<ScrubberPumpDirection>())
        {
            _pumpDirection.AddItem(GetPumpDirectionName(value), (int) value);
        }

        _pumpDirection.SelectId((int) _data.PumpDirection);
        _pumpDirection.OnItemSelected += args =>
        {
            _pumpDirection.SelectId(args.Id);
            _data.PumpDirection = (ScrubberPumpDirection) args.Id;
            ScrubberDataChanged?.Invoke(_address, _data);
        };
        _pumpDirection.Disabled = data.AirAlarmPanicWireCut;

        _copySettings.OnPressed += _ =>
        {
            ScrubberDataCopied?.Invoke(_data);
        };

        foreach (var gas in Enum.GetValues<Gas>())
        {
            var label = new Label
            {
                Text = gas.ToString(),
                MinWidth = 120
            };

            var gasButton = new Button
            {
                Name = gas.ToString(),
                Text = Loc.GetString("phrase-scrub").ToUpper(),
                ToggleMode = true,
                Pressed = _data.FilterGases.Contains(gas)
            };
            gasButton.OnToggled += args =>
            {
                if (args.Pressed)
                    _data.FilterGases.Add(gas);
                else
                    _data.FilterGases.Remove(gas);

                ScrubberDataChanged?.Invoke(_address, _data);
            };

            var limitSet = _data.FilterGasLimits.TryGetValue(gas, out var gasLimit);
            var percentInput = new FloatSpinBox
            {
                Name = gas.ToString() + "Percent",
                ToolTip = Loc.GetString("air-alarm-ui-atmos-gas-filter-percentage-tooltip"),
                Value = limitSet ? gasLimit : 0,
                HorizontalExpand = true,
            };
            percentInput.OnValueChanged += args =>
            {
                if (args.Value <= 0)
                {
                    _data.FilterGasLimits.Remove(gas);
                }
                else
                {
                    _data.FilterGasLimits[gas] = Math.Min(args.Value, 100);
                }

                ScrubberDataChanged?.Invoke(_address, _data);
            };

            var label2 = new Label
            {
                Text = Loc.GetString("air-alarm-ui-atmos-gas-filter-above")
            };

            var container = new GridContainer
            {
                Name = "CGasContainerRow" + gas.ToString(),
                Columns = 4,
                Children = { label, gasButton, label2, percentInput }
            };
            _gasControls.Add(gas, gasButton);
            _gasLimitControls.Add(gas, percentInput);
            _gases.AddChild(container);
        }

    }

    public void ChangeData(GasVentScrubberData data)
    {
        _data.Enabled = data.Enabled;
        _enabled.Pressed = _data.Enabled;

        _data.PumpDirection = data.PumpDirection;
        _pumpDirection.Select((int) _data.PumpDirection);
        _pumpDirection.Disabled = data.AirAlarmPanicWireCut;

        _data.VolumeRate = data.VolumeRate;
        _volumeRate.Value = _data.VolumeRate;

        _data.WideNet = data.WideNet;
        _wideNet.Pressed = _data.WideNet;
        _data.FilterGases = data.FilterGases;

        foreach (var gas in Enum.GetValues<Gas>())
        {
            _gasControls[gas].Pressed = data.FilterGases.Contains(gas);

            var limitSet = _data.FilterGasLimits.TryGetValue(gas, out var gasLimit);
            _gasLimitControls[gas].Value = limitSet ? gasLimit : 0;
        }
    }

    private static string GetPumpDirectionName(ScrubberPumpDirection direction) => direction switch
    {
        ScrubberPumpDirection.Siphoning => Loc.GetString("air-alarm-ui-scrubber-direction-siphoning"),
        ScrubberPumpDirection.Scrubbing => Loc.GetString("air-alarm-ui-scrubber-direction-scrubbing"),
        _ => direction.ToString()
    };
}
