using Content.Shared._DV.CCVars;
using Content.Shared._Kritters.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._DV.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class DeltaTab : Control
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public DeltaTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        DisableFiltersCheckBox.OnToggled += OnCheckBoxToggled;
        DisableFiltersCheckBox.Pressed = _cfg.GetCVar(DCCVars.NoVisionFilters);
        BloodColoredPainAuraCheckBox.OnToggled += OnCheckBoxToggled;
        BloodColoredPainAuraCheckBox.Pressed = _cfg.GetCVar(KrittersCCVars.BloodColoredPainAura);

        ApplyButton.OnPressed += OnApplyButtonPressed;
        UpdateApplyButton();
    }

    private void OnCheckBoxToggled(BaseButton.ButtonToggledEventArgs args)
    {
        UpdateApplyButton();
    }

    private void OnApplyButtonPressed(BaseButton.ButtonEventArgs args)
    {
        _cfg.SetCVar(DCCVars.NoVisionFilters, DisableFiltersCheckBox.Pressed);
        _cfg.SetCVar(KrittersCCVars.BloodColoredPainAura, BloodColoredPainAuraCheckBox.Pressed);

        _cfg.SaveToFile();
        UpdateApplyButton();
    }

    private void UpdateApplyButton()
    {
        var isNoVisionFiltersSame = DisableFiltersCheckBox.Pressed == _cfg.GetCVar(DCCVars.NoVisionFilters);
        var isBloodColoredPainAuraSame = BloodColoredPainAuraCheckBox.Pressed == _cfg.GetCVar(KrittersCCVars.BloodColoredPainAura);

        ApplyButton.Disabled = isNoVisionFiltersSame && isBloodColoredPainAuraSame;
    }
}
