name: Close PRs on master

on:
  pull_request_target:
    types: [ opened, ready_for_review ]

permissions:
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{ github.head_ref == 'master' || github.head_ref == 'main' || github.head_ref == 'develop' }}

    steps:
    - uses: actions/github-script@v8
      with:
        script: |
          const body = "Thank you for your contribution! It appears you created a PR from your master branch, this is [something you should avoid doing](https://jmeridth.com/posts/do-not-issue-pull-requests-from-your-master-branch/), and thus this PR has been automatically closed.\n\nWe suggest you follow [our git usage documentation](https://docs.spacestation14.com/en/general-development/setup/git-for-the-ss14-developer.html).\n\nYou can move your current work from the master branch to another branch by following [these commands](https://ohshitgit.com/#accidental-commit-master). And then you may recreate your PR using the new branch.";
          await github.rest.issues.createComment({
            ...context.repo,
            issue_number: context.issue.number,
            body,
          });
          await github.rest.pulls.update({
            ...context.repo,
            pull_number: context.issue.number,
            state: "closed",
          });
